---
- hosts: sharingan
  remote_user: guto2
  tasks:
    - name: "swap off"
      shell: swapoff -a && sed -i '/swap/d' /etc/fstab
      become: yes
      become_method: sudo
      become_user: root

    - name: "Kubeadm init"
      shell: kubeadm init 
      become: yes
      become_method: sudo

    - name: Show kubeadm join
      shell: grep 'kubeadm join --token' kubeadm-init.log
      register: token
      become: yes
      become_user: root
      become_method: sudo
     
    - name: "Line in File"
      lineinfile:
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        state: absent
        regexp: '^Environment="KUBELET_NETWORK_ARGS'
      become: yes
      become_method: sudo
      become_user: root

    - name: "Create .kube directory"
      file:
        path: "/{{ansible_env.HOME}}/.kube"
        state: directory
        mode: 0755
      become: yes
      become_method: sudo
     
    - name: "Create owner" 
      file:
        path: "{{ansible_env.HOME}}/.kube/config owner={{ansible_env.USER}}"
        state: touch
      become: yes
      become_method: sudo

    - name: "copy admin.conf to user's kube config"
      ignore_errors: yes
      command: cp /etc/kubernetes/admin.conf {{ansible_env.HOME}}/.kube/config
      become: yes
      become_method: sudo

    - name: "install pod network"
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
